export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const SET_TITLE = "SET_TITLE";

export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const SENDCODE_SUCCESS = "SENDCODE_SUCCESS";
export const SENDCODE_FAIL = "SENDCODE_FAIL";

export const VALIDATE_CODE_SUCCESS = "VALIDATE_CODE_SUCCESS";
export const VALIDATE_CODE_FAIL = "VALIDATE_CODE_FAIL";

export const SET_SALES_LIST = "SET_SALES_LIST";
export const SET_TT_DON_VI = "SET_TT_DON_VI";
export const SET_NGANH_HANG_LIST = "SET_NGANH_HANG_LIST";
export const SET_CURRENT_DON_VI = "SET_CURRENT_DON_VI";
export const SET_LOAI_DANHMUC_THUCHI = "SET_LOAI_DANHMUC_THUCHI";
export const SET_TINHTRANG_DONHANG = "SET_TINHTRANG_DONHANG";

export const RE_FETCH_DATA = "RE_FETCH_DATA";
export const LOAD_DATA_ORDERED = "LOAD_DATA_ORDERED";

export const SHOW_FOOTER = 'SHOW_FOOTER';
export const SET_SELECTED_CUSTOMER = 'SET_SELECTED_CUSTOMER'
export const SET_LIST_HTTT = 'SET_LIST_HTTT';